# CloudNative PostgreSQL database definition
# Uses the CloudNative PG operator to create and manage a PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-db
  namespace: default
spec:
  # Use latest PostgreSQL 17.3 image from CloudNative PG
  imageName: ghcr.io/cloudnative-pg/postgresql:17.3-bookworm
  
  # TODO: Configure appropriate instance count for high availability
  # How many database instances do we need for proper fault tolerance?
  instances: 1  # This provides no high availability - needs to be increased
  
  # Persistent volume storage configuration
  storage:
    size: 10Gi  # 10GB storage per instance
    storageClass: openebs-hostpath
  
  # Initial database setup
  bootstrap:
    initdb:
      database: tododb            # Initial database name
      owner: todo-demo-app        # Database owner (used for application connections)
  
  # PostgreSQL configuration parameters
  postgresql:
    parameters:
      shared_buffers: "256MB"    # Memory allocated for shared data/index caching
  
  # Update strategy for major version upgrades
  # "unsupervised" means operator won't block upgrades
  primaryUpdateStrategy: unsupervised
  
  # Enable Prometheus monitoring via PodMonitor custom resource
  # Will create metrics endpoint for database performance monitoring
  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "1024Mi"
      cpu: "100m"
    limits:
      memory: "1512Mi"
      cpu: "400m"
