# CloudNative PostgreSQL database definition
# Uses the CloudNative PG operator to create and manage a PostgreSQL cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: todo-db
  namespace: default
spec:
  # Use latest PostgreSQL 17.3 image from CloudNative PG
  imageName: ghcr.io/cloudnative-pg/postgresql:17.3-bookworm
  
  # Basic single-node PostgreSQL instance for development/workshop
  instances: 1
  
  # Persistent volume storage configuration
  storage:
    size: 1Gi  # 1GB storage per instance - minimal for workshop
    storageClass: openebs-hostpath
  
  # Initial database setup
  bootstrap:
    initdb:
      database: tododb            # Initial database name
      owner: todo-demo-app        # Database owner (used for application connections)
  
  # Basic PostgreSQL configuration parameters
  postgresql:
    parameters:
      shared_buffers: "128MB"    # Reduced memory allocation for workshop environment
  
  # Update strategy for major version upgrades
  primaryUpdateStrategy: unsupervised
  
  # Disable monitoring for basic setup
  monitoring:
    enablePodMonitor: false

  # Minimal resource requirements for workshop
  resources:
    requests:
      memory: "256Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
