---
# Application ConfigMap - centralized non-sensitive configuration
# Basic configuration for the db branch (minimal setup)
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-demo-app-config
  namespace: default
data:
  # AI configuration - disabled in db branch
  langchain4j-openai-api-key: "disabled"
  
  # Basic logging configuration
  quarkus-log-level: "INFO"      # Default logging level
  quarkus-log-console-json: "false"   # Use plain text logging for readability
  
  # Minimized JVM settings for Kubernetes
  java-opts: "-XX:+UseG1GC -XX:+ExitOnOutOfMemoryError"
