---
# Application ConfigMap - minimal configuration for starter branch
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-demo-app-config
  namespace: default
data:
  # Basic logging configuration
  quarkus-log-level: "INFO"
  quarkus-log-console-json: "false"
  
  # Basic JVM settings
  java-opts: "-XX:+UseG1GC"
