---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-demo-app-config
  namespace: todo-demo-app
data:
  # AI configuration
  langchain4j-openai-api-key: "demo"
  # Logging configuration
  quarkus-log-level: "INFO"
  langchain4j-log-requests: "true"
  langchain4j-log-responses: "true"
  quarkus-log-console-json: "true"
  # Metrics configuration
  quarkus-smallrye-metrics-path: "/q/metrics"
  quarkus-smallrye-metrics-extensions-enabled: "true"
  quarkus-smallrye-metrics-jaxrs-enabled: "true"
  # Optimized JVM settings for Kubernetes
  java-opts: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ExitOnOutOfMemoryError -XX:+AlwaysPreTouch -XX:+HeapDumpOnOutOfMemoryError"
