---
# Horizontal Pod Autoscaler (HPA) Configuration
# Automatically scales the number of pods based on resource utilization
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todo-demo-app-hpa
  namespace: default
spec:
  # Reference to the target deployment to scale
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-demo-app
  
  # Scaling boundaries - won't scale below min or above max
  minReplicas: 2   # Ensures high availability with minimum 2 pods
  maxReplicas: 5   # Upper limit to prevent runaway scaling
  
  # TODO: Configure metrics for autoscaling decisions
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 0  # TODO: Set appropriate CPU utilization percentage
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 0  # TODO: Set appropriate memory utilization percentage
  
  # TODO: Configure scaling behavior to prevent thrashing
  behavior:
    # Scale up configuration - how aggressively to add pods
    scaleUp:
      stabilizationWindowSeconds: 0  # TODO: Set appropriate stabilization window
      policies:
      - type: Pods
        value: 1                     # How many pods to add at once
        periodSeconds: 0             # TODO: Set appropriate period
    
    # Scale down configuration - how cautiously to remove pods
    scaleDown:
      stabilizationWindowSeconds: 0  # TODO: Set appropriate stabilization window
      policies:
      - type: Pods
        value: 1                     # How many pods to remove at once
        periodSeconds: 0             # TODO: Set appropriate period