apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List all the YAML files that should be included in the deployment
# Starter branch: minimal configuration (no database, no scaling, no monitoring)
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  
# Specify that participants MUST set their namespace
namespace: CHANGE_ME_TO_YOUR_ASSIGNED_NAMESPACE

# Add a name prefix to avoid conflicts between participants
namePrefix: PARTICIPANT_NAME-

# Configure common labels for all resources
commonLabels:
  app.kubernetes.io/part-of: todo-workshop
  participant: PARTICIPANT_NAME

# Image transformation to use participant-specific container image
images:
  - name: registry.hacknight043.coffeesprout.dev/todo-demo-app
    newName: registry.hacknight043.coffeesprout.dev/PARTICIPANT_NAME/todo-demo-app
    newTag: latest

# Patch the resources to fix references affected by namePrefix
patches:
  # Patch the ingress to have a unique hostname for each participant
  - target:
      kind: Ingress
      name: todo-demo-app-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: todo-PARTICIPANT_NAME.hacknight043.coffeesprout.dev
      - op: replace
        path: /spec/tls/0/hosts/0
        value: todo-PARTICIPANT_NAME.hacknight043.coffeesprout.dev
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: todo-PARTICIPANT_NAME.hacknight043.coffeesprout.dev
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: PARTICIPANT_NAME-todo-demo-app
      - op: replace
        path: /spec/tls/0/secretName
        value: PARTICIPANT_NAME-todo-demo-app-tls
  
  # Removed patches for HPA, PodDisruptionBudget, and ServiceMonitor 
  # as they are not included in the starter branch resources
