---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: todo-demo-app-network-policy
  namespace: todo-demo-app
spec:
  podSelector:
    matchLabels:
      app: todo-demo-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: todo-db
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
      endPort: 53
    - protocol: UDP
      port: 53
      endPort: 53