---
# Pod Disruption Budget (PDB) Configuration
# Controls how many pods can be down simultaneously during voluntary disruptions
# Examples of voluntary disruptions: node drains during upgrades, autoscaling down
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-demo-app-pdb
  namespace: default
spec:
  # Ensures at least 1 pod is always available during disruptions
  # This prevents all pods from being taken down at once
  # Combined with minReplicas: 2 in HPA, this ensures 50% availability
  minAvailable: 1
  
  # Alternative approach would be to use maxUnavailable: 1 (or 50%)
  # maxUnavailable: 1
  
  # Select which pods this budget applies to
  selector:
    matchLabels:
      app: todo-demo-app

