---
# Pod Disruption Budget (PDB) Configuration
# Controls how many pods can be down simultaneously during voluntary disruptions
# Examples of voluntary disruptions: node drains during upgrades, autoscaling down
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-demo-app-pdb
  namespace: default
spec:
  # TODO: Configure either minAvailable or maxUnavailable (but not both)
  # minAvailable ensures a minimum number of pods are always available
  # maxUnavailable limits how many pods can be down at once
  
  # Option 1: Use minAvailable to ensure a minimum number of pods
  # minAvailable: ?
  
  # Option 2: Use maxUnavailable to limit pods down during disruption
  # maxUnavailable: ?
  
  # Select which pods this budget applies to
  selector:
    matchLabels:
      app: todo-demo-app

