---
# Prometheus ServiceMonitor Configuration
# Instructs Prometheus to collect metrics from our application
# This is a custom resource defined by the Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-demo-app
  namespace: default
  labels:
    # This label is used by Prometheus to discover this ServiceMonitor
    # Must match the Prometheus Operator's label selector
    release: prometheus
spec:
  # Select which services to monitor based on label matching
  selector:
    matchLabels:
      app: todo-demo-app  # Must match service labels
  # TODO: Configure metrics scraping
  endpoints:
  - port: http            # This should match the port name in the Service definition
    path: ""              # TODO: What is the correct metrics endpoint for Quarkus?
    interval: ""          # TODO: How often should Prometheus scrape metrics?
    # Additional settings you might want to configure:
    # scrapeTimeout: ?    # How long before timing out a scrape request
    # honorLabels: ?      # Whether to preserve application-supplied labels