---
# Prometheus ServiceMonitor Configuration
# Instructs Prometheus to collect metrics from our application
# This is a custom resource defined by the Prometheus Operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-demo-app
  namespace: quarkus-k8s-barry
  labels:
    # This label is used by Prometheus to discover this ServiceMonitor
    # Must match the Prometheus Operator's label selector
    release: prometheus
spec:
  # Select which services to monitor based on label matching
  selector:
    matchLabels:
      app: todo-demo-app  # Must match service labels
  # Configuration for metrics scraping
  endpoints:
  - port: http            # Must match port name in Service definition
    path: /q/metrics      # Quarkus metrics endpoint (MicroProfile Metrics)
    interval: 15s         # Scrape every 15 seconds
    # Optional settings we could add:
    # scrapeTimeout: 10s  # Timeout for scrape requests
    # honorLabels: true   # Preserve application-supplied labels