---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-demo-app
  namespace: todo-demo-app
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: todo-demo-app
  endpoints:
  - port: http
    path: /q/metrics
    interval: 15s